- color: "c2f232"
  description: A good first issue to get started with.
  name: good first issue
- color: "166894"
  description: A good issue for a mentorship project.
  name: good for mentorship
- color: "008672"
  description: Need some extra hands to the this done.
  name: help wanted
